### ISSUE TITLE
Change python to 3.7

### ISSUE THREAD

**Issue by DonFlymoor** [AshSidney/ARTKBlender#17]
This is a great idea, but I can't figure out how to use it. I downloaded the demo, but it does not run in UPBGE 0.2.5, with this error message:
```python
Error: cont(Camera), Python script error
Traceback (most recent call last):
  File "initPatt.py", line 2, in <module>
ImportError: DLL load failed: The specified module could not be found.
Error: cont1(Plane), Python script error
Traceback (most recent call last):
  File "detect.py", line 3, in <module>
ImportError: DLL load failed: The specified module could not be found.
Blender Game Engine Finished
```

**Comment by DonFlymoor** [comment]
Ok, I figured out the problem. It uses python 3.5, while UPBGE uses 3.7. So I suppose that will have to be changed first...
